### PR TITLE
Prevented dereferencing of 'nil' pointer in Close function. You run into this issue when you try to make a connection, but the host does not exist.

### PR DESCRIPTION
**Pull request by varun1729**

### CODE REVIEW

**Comment by mtfelian** [comment]
Thank you. It is bad thing if a receiver becomes nil, but I merge it as a fast solution. 

Is it right that problem is in the parameter c.event due to c may be nil ?

**Comment by varun1729** [comment]
Yes c is nil, I think it might be because of this
```
	c.conn, err = tr.Connect(addr)
	if err != nil {
		return nil, err
	}
```
Since a connection was not established, nil was returned. Consequently any operation on c will error.
Thank-you for maintaining a fork of graah/golang-socket.io . This has been useful.

**Comment by mtfelian** [comment]
I will take a closer look on it this week.

**Comment by mtfelian** [comment]
@varun1729 why you don't check this in your code?

**Comment by mtfelian** [comment]
Use the valid pattern for this: 
```
c, err := socketio.Dial("something", tr)
if err != nil {
  // do something
}
```

**Comment by varun1729** [comment]
@mtfelian This is what I am doing.. Maybe it is the defer?
```
client, err := gosocketio.Dial("wss://"+host+"/test/socket.io", transport.NewWebsocketTransport(transport.WebsocketTransportParams{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	}))
	defer client.Close()
	if err != nil {
		return nil, err
	}
```

**Comment by mtfelian** [comment]
You should place your defer after err checking.

**Pull request merged**
